<a href="https://colab.research.google.com/github/jujjurirakeshkumar47-lang/my-first-repo/blob/main/work.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
string1 ='jujjuri-rakesh-kumar'

In [ ]:
string1 ='jujjuri-rakesh-kumar'

string1.split('-')

['jujjuri', 'rakesh', 'kumar']

In [ ]:
with open("student_marks","a") as file :
    file.write("= * 30")

In [ ]:
with open ("student_marks","w") as file :
    file.write("my name is rakesh\n")
    file.write("i'm from vijayawada\n")
    file.write("im 22 years old\n")


In [ ]:
with open("student_marks","a") as file:
  file.write("-*30")

In [ ]:
with open("student_marks","r") as file:
  rrr = file.read()
print (rrr)

my name is rakesh
i'm from vijayawada
im 22 years old
-*30


In [ ]:
with open("application","w") as file :
  file.write("----------user input ----------\n")

In [ ]:
with open("application","a")as file :
  file.write("---OPEN APPLICATION---\n")
  file.write("---ENTER USER NAME---\n")
  file.write("---ENTER PASSWORD---\n")
  file.write("---ECHECK BALANCE---\n")
  file.write("---CLOSED APP;ICATION---\n")

In [ ]:
with open("application","r") as file :
  relult = file.read()
  print(relult)

----------user input ----------
---OPEN APPLICATION---
---ENTER USER NAME---
---ENTER PASSWORD---
---ECHECK BALANCE---
---CLOSED APP;ICATION---



In [ ]:
with open("application","r") as file :
  line1 = file.readline()

In [ ]:
print(line1)

----------user input ----------



In [ ]:
with open("application","r") as file :
  line1 = file.readlines()
  print (line1)

['----------user input ----------\n', '---OPEN APPLICATION---\n', '---ENTER USER NAME---\n', '---ENTER PASSWORD---\n', '---ECHECK BALANCE---\n', '---CLOSED APP;ICATION---\n']


In [ ]:
search_name =  '---ENTER USER NAME---'

with open("application","r") as file :
  for line in file:
    if search_name in line:
      print(line)

---ENTER USER NAME---



ARRAYS


In [ ]:
import numpy as np


In [ ]:
r = np.array([[[2,2],[3,3],[4,4],[5,5]]])
print(r.shape)
print(r)

(1, 4, 2)
[[[2 2]
  [3 3]
  [4 4]
  [5 5]]]


In [ ]:
print(r.T)
print(r.shape)

[[[2]
  [3]
  [4]
  [5]]

 [[2]
  [3]
  [4]
  [5]]]
(1, 4, 2)


In [ ]:
numbers = np.arange (1, 10)
print(numbers)
print(numbers.shape)


[1 2 3 4 5 6 7 8 9]
(9,)


In [ ]:
table = numbers.reshape(1,3,3)
print(table)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]]


In [ ]:
num = np.arange(1,10)
print(num)

[1 2 3 4 5 6 7 8 9]


In [ ]:
num = np.reshape(3,-1)
print(num)

[3]


In [ ]:
for i in range (1,10):
  print(i , end=',')

1,2,3,4,5,6,7,8,9,

TASK


In [ ]:
import numpy as np

np.random.seed(7)

num_students =20

first_name = np.random.choice(['rakesh','kumar','jujjuri','sumanth','irfan','mastan','yesu'] , size =num_students)
print(first_name)



['irfan' 'kumar' 'yesu' 'sumanth' 'sumanth' 'irfan' 'kumar' 'yesu'
 'rakesh' 'kumar' 'yesu' 'jujjuri' 'jujjuri' 'rakesh' 'yesu' 'irfan'
 'rakesh' 'irfan' 'rakesh' 'sumanth']


In [ ]:
cities =np.random.choice (['ongole','vijayawada','hyd','channai','mumbai''goa','vizag'] , size = num_students)
print(cities)

['hyd' 'channai' 'mumbaigoa' 'mumbaigoa' 'vizag' 'ongole' 'ongole' 'vizag'
 'ongole' 'channai' 'vizag' 'ongole' 'hyd' 'ongole' 'vijayawada'
 'mumbaigoa' 'vijayawada' 'channai' 'channai' 'ongole']


In [ ]:
ages = np.random.randint(20,30,size = num_students)
print(ages)

[23 20 21 20 20 26 27 27 29 23 20 27 27 27 20 25 24 23 21 23]


In [ ]:
maths = np.random.randint(70,80 ,size = num_students)
print(maths)

[71 73 74 73 71 79 75 79 71 72 73 72 72 75 77 73 70 79 79 73]


In [ ]:
economis = np.random.randint(40,60 ,size = num_students)
print(economis)

[54 54 55 43 56 44 51 48 51 55 53 58 47 43 52 52 55 48 46 46]


In [ ]:
marketing = np.random.randint(90,100 ,size = num_students)
print(marketing)

[95 97 91 95 94 94 99 99 90 96 92 96 98 92 94 91 96 91 95 91]


In [ ]:
english = np.random.randint(72,88 ,size = num_students)
print(english)

[78 84 81 80 84 78 87 77 81 79 77 76 83 84 81 83 78 80 73 77]


In [ ]:
import numpy as np

np.random.seed(7)

num_students =20

first_name = np.random.choice(['rakesh','kumar','jujjuri','sumanth','irfan','mastan','yesu'] , size =num_students)
print(first_name)

cities =np.random.choice (['ongole','vijayawada','hyd','channai','mumbai','goa','vizag'] , size = num_students)
print(cities)

age = np.random.randint(20,30,size = num_students)
print(age)

maths = np.random.randint(70,80 ,size = num_students)
print(maths)

economis = np.random.randint(40,60 ,size = num_students)
print(economis)

marketing = np.random.randint(90,100 ,size = num_students)
print(marketing)

english = np.random.randint(72,88 ,size = num_students)
print(english)

['irfan' 'kumar' 'yesu' 'sumanth' 'sumanth' 'irfan' 'kumar' 'yesu'
 'rakesh' 'kumar' 'yesu' 'jujjuri' 'jujjuri' 'rakesh' 'yesu' 'irfan'
 'rakesh' 'irfan' 'rakesh' 'sumanth']
['hyd' 'vizag' 'channai' 'mumbai' 'mumbai' 'goa' 'ongole' 'ongole' 'goa'
 'ongole' 'channai' 'goa' 'ongole' 'hyd' 'ongole' 'vijayawada' 'vizag'
 'vizag' 'mumbai' 'vizag']
[29 27 23 23 28 23 20 21 20 20 26 27 27 29 23 20 27 27 27 20]
[75 74 73 71 73 71 73 74 73 71 79 75 79 71 72 73 72 72 75 77]
[43 51 55 56 52 51 49 49 52 43 54 54 55 43 56 44 51 48 51 55]
[97 92 97 93 98 96 96 95 96 95 97 91 95 94 94 99 99 90 96 92]
[84 78 80 74 83 82 86 76 73 85 78 82 73 77 87 73 78 84 81 80]


In [ ]:
import numpy as np

np.random.seed(7)

num_students =20

first_name = np.random.choice(['rakesh','kumar','jujjuri','sumanth','irfan','mastan','yesu'] , size =num_students)
print(first_name)

cities =np.random.choice (['ongole','vijayawada','hyd','channai','mumbai','goa','vizag'] , size = num_students)
print(cities)

age = np.random.randint(20,30,size = num_students)
print(age)

maths = np.random.randint(70,80 ,size = num_students)
print(maths)

economis = np.random.randint(40,60 ,size = num_students)
print(economis)

marketing = np.random.randint(90,100 ,size = num_students)
print(marketing)

english = np.random.randint(72,88 ,size = num_students)
print(english)

['irfan' 'kumar' 'yesu' 'sumanth' 'sumanth' 'irfan' 'kumar' 'yesu'
 'rakesh' 'kumar' 'yesu' 'jujjuri' 'jujjuri' 'rakesh' 'yesu' 'irfan'
 'rakesh' 'irfan' 'rakesh' 'sumanth']
['hyd' 'vizag' 'channai' 'mumbai' 'mumbai' 'goa' 'ongole' 'ongole' 'goa'
 'ongole' 'channai' 'goa' 'ongole' 'hyd' 'ongole' 'vijayawada' 'vizag'
 'vizag' 'mumbai' 'vizag']
[29 27 23 23 28 23 20 21 20 20 26 27 27 29 23 20 27 27 27 20]
[75 74 73 71 73 71 73 74 73 71 79 75 79 71 72 73 72 72 75 77]
[43 51 55 56 52 51 49 49 52 43 54 54 55 43 56 44 51 48 51 55]
[97 92 97 93 98 96 96 95 96 95 97 91 95 94 94 99 99 90 96 92]
[84 78 80 74 83 82 86 76 73 85 78 82 73 77 87 73 78 84 81 80]


In [ ]:
with open("num_students.txt","w") as file:
  file.write("name,cities,age,maths,economics,marketing,english")

In [ ]:
import numpy as np

# From a Python list
arr = np.array([1, 2, 3, 4, 5])

# Arrays filled with zeros or ones
np.zeros((3, 4))          # 3 rows, 4 columns of zeros
np.ones((2, 3))           # 2 rows, 3 columns of ones

# Evenly spaced values
np.arange(0, 10, 2)       # [0, 2, 4, 6, 8] — like range(), but returns array
np.linspace(0, 1, 5)      # [0.0, 0.25, 0.5, 0.75, 1.0] — 5 evenly spaced floats


array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [ ]:
np.zeros((3, 4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
np.zeros((300000, 40000))

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [ ]:
np.ones((2, 3))


array([[1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
import numpy as np

np.random.seed(7)

num_students =20

first_name = np.random.choice(['rakesh','kumar','jujjuri','sumanth','irfan','mastan','yesu'] , size =num_students)
print(first_name)

cities =np.random.choice (['ongole','vijayawada','hyd','channai','mumbai','goa','vizag'] , size = num_students)
print(cities)

age = np.random.randint(20,30,size = num_students)
print(age)

maths = np.random.randint(70,80 ,size = num_students)
print(maths)

economis = np.random.randint(40,60 ,size = num_students)
print(economis)

marketing = np.random.randint(90,100 ,size = num_students)
print(marketing)

english = np.random.randint(72,88 ,size = num_students)
print(english)

with open("student_data","w") as file :
  file.write("first_name,cities,age,maths,economics,marketing,english")

  for i in range(num_students):
    file.write(f"{first_name[i]},{cities[i]},{age[i]},{maths[i]},{economis[i]},{marketing[i]},{english[i]}\n")

['irfan' 'kumar' 'yesu' 'sumanth' 'sumanth' 'irfan' 'kumar' 'yesu'
 'rakesh' 'kumar' 'yesu' 'jujjuri' 'jujjuri' 'rakesh' 'yesu' 'irfan'
 'rakesh' 'irfan' 'rakesh' 'sumanth']
['hyd' 'vizag' 'channai' 'mumbai' 'mumbai' 'goa' 'ongole' 'ongole' 'goa'
 'ongole' 'channai' 'goa' 'ongole' 'hyd' 'ongole' 'vijayawada' 'vizag'
 'vizag' 'mumbai' 'vizag']
[29 27 23 23 28 23 20 21 20 20 26 27 27 29 23 20 27 27 27 20]
[75 74 73 71 73 71 73 74 73 71 79 75 79 71 72 73 72 72 75 77]
[43 51 55 56 52 51 49 49 52 43 54 54 55 43 56 44 51 48 51 55]
[97 92 97 93 98 96 96 95 96 95 97 91 95 94 94 99 99 90 96 92]
[84 78 80 74 83 82 86 76 73 85 78 82 73 77 87 73 78 84 81 80]


In [ ]:
with open("student_data","r") as file :
 f1 = file.read()
 f2 = file.read()

 print(f1)
 print(f2)

first_name,cities,age,maths,economics,marketing,englishirfan,hyd,29,75,43,97,84
kumar,vizag,27,74,51,92,78
yesu,channai,23,73,55,97,80
sumanth,mumbai,23,71,56,93,74
sumanth,mumbai,28,73,52,98,83
irfan,goa,23,71,51,96,82
kumar,ongole,20,73,49,96,86
yesu,ongole,21,74,49,95,76
rakesh,goa,20,73,52,96,73
kumar,ongole,20,71,43,95,85
yesu,channai,26,79,54,97,78
jujjuri,goa,27,75,54,91,82
jujjuri,ongole,27,79,55,95,73
rakesh,hyd,29,71,43,94,77
yesu,ongole,23,72,56,94,87
irfan,vijayawada,20,73,44,99,73
rakesh,vizag,27,72,51,99,78
irfan,vizag,27,72,48,90,84
rakesh,mumbai,27,75,51,96,81
sumanth,vizag,20,77,55,92,80




In [ ]:
with open ("warehouse_data.txt","w") as file:
  file.write("120\n 85\n 200\n 95\n 150\n")
  # a - append will add data at last of a existing file without deleting file

In [ ]:
#TASK 2
with open ("warehouse_data.txt","r") as file:
  files = file.readlines()
  #Before
print(files)

#After
for file in files :
  print(file.strip())

  '''read and readlines are just helps to read data in a single line
   but to remove unwanted data its better to use strip'''



['120\n', ' 85\n', ' 200\n', ' 95\n', ' 150\n']
120
85
200
95
150


In [ ]:
import numpy as np

arr = np.array([120, 85, 200, 95, 150])
print("Array:", arr)
print("Dtype:", arr.dtype)
print("Shape:", arr.shape)
print("Size:", arr.size)

# statistics
print("Sum:", np.sum(arr))
print("Max:", np.max(arr))
print("Min:", np.min(arr))
# All numbers → int64
# Mix of number + text → string

Array: [120  85 200  95 150]
Dtype: int64
Shape: (5,)
Size: 5
Sum: 650
Max: 200
Min: 85


In [ ]:
import numpy as np
np.random.seed(42)
no_stusents = 10
names = np.random.choice(["rakesh","kumar","jujjuri","irfan","srinivas"], size= no_stusents)
age = np.random.randint(15,18, size= no_stusents)
maths =np.random.randint(40,100 , size= no_stusents)
science = np.random.randint(40,100 , size= no_stusents)
english = np.random.randint(40,100 , size= no_stusents)
marks = np.array([maths, science, english])
print("Shape:", marks.shape)
print("Dtype:", marks.dtype)

with open("student_data.txt","w") as file :
  file.write("names age maths science english\n")
  for i in range(no_stusents):
    file.write(f"{names[i]}  ,{age[i]}  ,{maths[i]}  ,{science[i]}  ,{english[i]}\n")



Shape: (3, 10)
Dtype: int64


In [ ]:
#TASK 1
import numpy as np
np.random.seed(42)
students = 10
names = np.random.choice(["rakesh" ,  "kumar" , "jujjuri" ,  "srinu" ,  "dinakar"] , size = students )
age = np.random.randint(15 , 18, size = students)
maths = np.random.randint(40 , 100 , size = students)
science = np.random.randint(40 , 100 , size = students)
english = np.random.randint(40 , 100 , size = students)
marks=np.array([maths,science,english])


print(marks.dtype)
print(marks.shape)


int64
(3, 10)


In [ ]:
print("orginal_shaped_marks :\n",marks)
reshaped_marks =marks.reshape(2, 5 , 3)
print(reshaped_marks)

print('first five students marks :',marks [:5,:2])

#(2, 5, 3) means 2 dimensions and 5 rows and 3 columns

orginal_shaped_marks :
 [[61 83 64 88 66 98 81 67 99 55]
 [54 86 90 83 94 91 96 42 76 90]
 [46 60 48 78 57 43 64 99 53 89]]
[[[61 83 64]
  [88 66 98]
  [81 67 99]
  [55 54 86]
  [90 83 94]]

 [[91 96 42]
  [76 90 46]
  [60 48 78]
  [57 43 64]
  [99 53 89]]]
first five students marks : [[61 83]
 [54 86]
 [46 60]]


In [ ]:
with open ("student_data.txt","w")as file :
  file.write(' names   | age   | maths  | science  | english \n')


  for i in range(students):
    file.write(f'{names[i]}   | {age[i]} | {maths[i]}  | {science[i]}   | {english[i]} \n'  )

    print("✅ All student records saved successfully!")




✅ All student records saved successfully!
✅ All student records saved successfully!
✅ All student records saved successfully!
✅ All student records saved successfully!
✅ All student records saved successfully!
✅ All student records saved successfully!
✅ All student records saved successfully!
✅ All student records saved successfully!
✅ All student records saved successfully!
✅ All student records saved successfully!


In [ ]:
with open("student_data.txt", "r") as file:
    print("\n📄 File Contents:\n")
    for line in file:
        print(line.strip())



📄 File Contents:

names   | age   | maths  | science  | english
srinu   | 17 | 61  | 54   | 46
dinakar   | 16 | 83  | 86   | 60
jujjuri   | 15 | 64  | 90   | 48
dinakar   | 16 | 88  | 83   | 78
dinakar   | 16 | 66  | 94   | 57
kumar   | 16 | 98  | 91   | 43
jujjuri   | 16 | 81  | 96   | 64
jujjuri   | 15 | 67  | 42   | 99
jujjuri   | 15 | 99  | 76   | 53
dinakar   | 16 | 55  | 90   | 89


In [ ]:
import numpy as np

# TASK 1
np.random.seed(42)
students = 10

names = np.random.choice(
    ["rakesh", "kumar", "jujjuri", "srinu", "dinakar"],
    size=students
)
age = np.random.randint(15, 18, size=students)
maths = np.random.randint(40, 100, size=students)
science = np.random.randint(40, 100, size=students)
english = np.random.randint(40, 100, size=students)

# FIXED shape
marks = np.array([maths, science, english]).T

print(marks.dtype)
print(marks.shape)

# TASK 2
print("\nOriginal Marks:\n", marks)

reshaped_marks = marks.reshape(2, 5, 3)
print("\nReshaped Marks:\n", reshaped_marks)

print("\nFirst 5 students (Maths & Science):\n", marks[:5, :2])

# (2, 5, 3) means:
# 2 groups, 5 students per group, 3 subjects per student

# TASK 3
with open("student_data.txt", "w") as file:
    file.write("Name | Age | Maths | Science | English\n")

    for i in range(students):
        file.write(
            f"{names[i]} | {age[i]} | {maths[i]} | {science[i]} | {english[i]}\n"
        )

print("\n✅ All student records saved successfully!")

# READ FILE
with open("student_data.txt", "r") as file:
    print("\n📄 File Contents:\n")
    for line in file:
        print(line.strip())

int64
(10, 3)

Original Marks:
 [[61 54 46]
 [83 86 60]
 [64 90 48]
 [88 83 78]
 [66 94 57]
 [98 91 43]
 [81 96 64]
 [67 42 99]
 [99 76 53]
 [55 90 89]]

Reshaped Marks:
 [[[61 54 46]
  [83 86 60]
  [64 90 48]
  [88 83 78]
  [66 94 57]]

 [[98 91 43]
  [81 96 64]
  [67 42 99]
  [99 76 53]
  [55 90 89]]]

First 5 students (Maths & Science):
 [[61 54]
 [83 86]
 [64 90]
 [88 83]
 [66 94]]

✅ All student records saved successfully!

📄 File Contents:

Name | Age | Maths | Science | English
srinu | 17 | 61 | 54 | 46
dinakar | 16 | 83 | 86 | 60
jujjuri | 15 | 64 | 90 | 48
dinakar | 16 | 88 | 83 | 78
dinakar | 16 | 66 | 94 | 57
kumar | 16 | 98 | 91 | 43
jujjuri | 16 | 81 | 96 | 64
jujjuri | 15 | 67 | 42 | 99
jujjuri | 15 | 99 | 76 | 53
dinakar | 16 | 55 | 90 | 89


In [ ]:
import pandas as pd


In [ ]:
df = pd.read_csv("/content/Titanic-Dataset.csv")
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C


In [ ]:
df.describe()

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,891.000000,891.000000,891.000000,714.000000,891.000000,891.000000,891.000000
mean,446.000000,0.383838,2.308642,29.699118,0.523008,0.381594,32.204208
std,257.353842,0.486592,0.836071,14.526497,1.102743,0.806057,49.693429
min,1.000000,0.000000,1.000000,0.420000,0.000000,0.000000,0.000000
25%,223.500000,0.000000,2.000000,20.125000,0.000000,0.000000,7.910400
50%,446.000000,0.000000,3.000000,28.000000,0.000000,0.000000,14.454200
75%,668.500000,1.000000,3.000000,38.000000,1.000000,0.000000,31.000000
max,891.000000,1.000000,3.000000,80.000000,8.000000,6.000000,512.329200


In [ ]:
df.shape

(891, 12)

In [ ]:
df.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')

In [ ]:
df.head(7)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
5,6,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S


In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  891 non-null    int64  
 1   Survived     891 non-null    int64  
 2   Pclass       891 non-null    int64  
 3   Name         891 non-null    object 
 4   Sex          891 non-null    object 
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64  
 7   Parch        891 non-null    int64  
 8   Ticket       891 non-null    object 
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object 
 11  Embarked     889 non-null    object 
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB


In [ ]:
df.describe()

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,891.000000,891.000000,891.000000,714.000000,891.000000,891.000000,891.000000
mean,446.000000,0.383838,2.308642,29.699118,0.523008,0.381594,32.204208
std,257.353842,0.486592,0.836071,14.526497,1.102743,0.806057,49.693429
min,1.000000,0.000000,1.000000,0.420000,0.000000,0.000000,0.000000
25%,223.500000,0.000000,2.000000,20.125000,0.000000,0.000000,7.910400
50%,446.000000,0.000000,3.000000,28.000000,0.000000,0.000000,14.454200
75%,668.500000,1.000000,3.000000,38.000000,1.000000,0.000000,31.000000
max,891.000000,1.000000,3.000000,80.000000,8.000000,6.000000,512.329200


In [ ]:
import seaborn as sns

titanic = sns .load_dataset("titanic")

In [ ]:
titanic["age"]

,age
0,22.0
1,38.0
2,26.0
3,35.0
4,35.0
...,...
886,27.0
887,19.0
888,NaN
889,26.0


In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  891 non-null    int64  
 1   Survived     891 non-null    int64  
 2   Pclass       891 non-null    int64  
 3   Name         891 non-null    object 
 4   Sex          891 non-null    object 
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64  
 7   Parch        891 non-null    int64  
 8   Ticket       891 non-null    object 
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object 
 11  Embarked     889 non-null    object 
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB


In [ ]:
titanic.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 15 columns):
 #   Column       Non-Null Count  Dtype   
---  ------       --------------  -----   
 0   survived     891 non-null    int64   
 1   pclass       891 non-null    int64   
 2   sex          891 non-null    object  
 3   age          714 non-null    float64 
 4   sibsp        891 non-null    int64   
 5   parch        891 non-null    int64   
 6   fare         891 non-null    float64 
 7   embarked     889 non-null    object  
 8   class        891 non-null    category
 9   who          891 non-null    object  
 10  adult_male   891 non-null    bool    
 11  deck         203 non-null    category
 12  embark_town  889 non-null    object  
 13  alive        891 non-null    object  
 14  alone        891 non-null    bool    
dtypes: bool(2), category(2), float64(2), int64(4), object(5)
memory usage: 80.7+ KB


In [ ]:
cln = titanic.select_dtypes(include="number")
print(cln)


     survived  pclass   age  sibsp  parch     fare
0           0       3  22.0      1      0   7.2500
1           1       1  38.0      1      0  71.2833
2           1       3  26.0      0      0   7.9250
3           1       1  35.0      1      0  53.1000
4           0       3  35.0      0      0   8.0500
..        ...     ...   ...    ...    ...      ...
886         0       2  27.0      0      0  13.0000
887         1       1  19.0      0      0  30.0000
888         0       3   NaN      1      2  23.4500
889         1       1  26.0      0      0  30.0000
890         0       3  32.0      0      0   7.7500

[891 rows x 6 columns]


In [ ]:
titanic.describe()

,survived,pclass,age,sibsp,parch,fare
count,891.000000,891.000000,714.000000,891.000000,891.000000,891.000000
mean,0.383838,2.308642,29.699118,0.523008,0.381594,32.204208
std,0.486592,0.836071,14.526497,1.102743,0.806057,49.693429
min,0.000000,1.000000,0.420000,0.000000,0.000000,0.000000
25%,0.000000,2.000000,20.125000,0.000000,0.000000,7.910400
50%,0.000000,3.000000,28.000000,0.000000,0.000000,14.454200
75%,1.000000,3.000000,38.000000,1.000000,0.000000,31.000000
max,1.000000,3.000000,80.000000,8.000000,6.000000,512.329200


In [ ]:
titanic_renamed = titanic.rename(columns= {"pclass": "ticketclass"})

titanic_renamed

,survived,ticketclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,0,2,male,27.0,0,0,13.0000,S,Second,man,True,NaN,Southampton,no,True
887,1,1,female,19.0,0,0,30.0000,S,First,woman,False,B,Southampton,yes,True
888,0,3,female,NaN,1,2,23.4500,S,Third,woman,False,NaN,Southampton,no,False
889,1,1,male,26.0,0,0,30.0000,C,First,man,True,C,Cherbourg,yes,True


In [ ]:
titanic.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 15 columns):
 #   Column       Non-Null Count  Dtype   
---  ------       --------------  -----   
 0   survived     891 non-null    int64   
 1   pclass       891 non-null    int64   
 2   sex          891 non-null    object  
 3   age          714 non-null    float64 
 4   sibsp        891 non-null    int64   
 5   parch        891 non-null    int64   
 6   fare         891 non-null    float64 
 7   embarked     889 non-null    object  
 8   class        891 non-null    category
 9   who          891 non-null    object  
 10  adult_male   891 non-null    bool    
 11  deck         203 non-null    category
 12  embark_town  889 non-null    object  
 13  alive        891 non-null    object  
 14  alone        891 non-null    bool    
dtypes: bool(2), category(2), float64(2), int64(4), object(5)
memory usage: 80.7+ KB


In [ ]:
titanic.describe()

,survived,pclass,age,sibsp,parch,fare
count,891.000000,891.000000,714.000000,891.000000,891.000000,891.000000
mean,0.383838,2.308642,29.699118,0.523008,0.381594,32.204208
std,0.486592,0.836071,14.526497,1.102743,0.806057,49.693429
min,0.000000,1.000000,0.420000,0.000000,0.000000,0.000000
25%,0.000000,2.000000,20.125000,0.000000,0.000000,7.910400
50%,0.000000,3.000000,28.000000,0.000000,0.000000,14.454200
75%,1.000000,3.000000,38.000000,1.000000,0.000000,31.000000
max,1.000000,3.000000,80.000000,8.000000,6.000000,512.329200


In [ ]:
titanic[1 : 5]

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True


In [ ]:
titanic.iloc[2,6]

np.float64(7.925)

In [ ]:
titanic.iloc[0:7,2]

,sex
0,male
1,female
2,female
3,female
4,male
5,male
6,male


In [ ]:
df.describe()

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,891.000000,891.000000,891.000000,714.000000,891.000000,891.000000,891.000000
mean,446.000000,0.383838,2.308642,29.699118,0.523008,0.381594,32.204208
std,257.353842,0.486592,0.836071,14.526497,1.102743,0.806057,49.693429
min,1.000000,0.000000,1.000000,0.420000,0.000000,0.000000,0.000000
25%,223.500000,0.000000,2.000000,20.125000,0.000000,0.000000,7.910400
50%,446.000000,0.000000,3.000000,28.000000,0.000000,0.000000,14.454200
75%,668.500000,1.000000,3.000000,38.000000,1.000000,0.000000,31.000000
max,891.000000,1.000000,3.000000,80.000000,8.000000,6.000000,512.329200


In [ ]:
print(df.dtypes)

PassengerId      int64
Survived         int64
Pclass           int64
Name            object
Sex             object
Age            float64
SibSp            int64
Parch            int64
Ticket          object
Fare           float64
Cabin           object
Embarked        object
dtype: object


In [ ]:
df.shape

(891, 12)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  891 non-null    int64  
 1   Survived     891 non-null    int64  
 2   Pclass       891 non-null    int64  
 3   Name         891 non-null    object 
 4   Sex          891 non-null    object 
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64  
 7   Parch        891 non-null    int64  
 8   Ticket       891 non-null    object 
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object 
 11  Embarked     889 non-null    object 
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB


In [ ]:
survivors = titanic[titanic["survived"]==1]
survivors.head(10)



,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
8,1,3,female,27.0,0,2,11.1333,S,Third,woman,False,NaN,Southampton,yes,False
9,1,2,female,14.0,1,0,30.0708,C,Second,child,False,NaN,Cherbourg,yes,False
10,1,3,female,4.0,1,1,16.7000,S,Third,child,False,G,Southampton,yes,False
11,1,1,female,58.0,0,0,26.5500,S,First,woman,False,C,Southampton,yes,True
15,1,2,female,55.0,0,0,16.0000,S,Second,woman,False,NaN,Southampton,yes,True
17,1,2,male,NaN,0,0,13.0000,S,Second,man,True,NaN,Southampton,yes,True
19,1,3,female,NaN,0,0,7.2250,C,Third,woman,False,NaN,Cherbourg,yes,True


In [ ]:
survivors.iloc[6:9 , 8:10]

,class,who
11,First,woman
15,Second,woman
17,Second,man


In [ ]:
from google.colab import drive
drive.mount('/content/drive')

In [ ]:
survivors.loc[[11,15,17] , ["class","who"]]

,class,who
11,First,woman
15,Second,woman
17,Second,man


In [ ]:
titanic.iloc[4:7,9:11]

,who,adult_male
4,man,True
5,man,True
6,man,True


In [ ]:
titanic.iloc[4:7 , 8:10]

,class,who
4,Third,man
5,Third,man
6,First,man


In [ ]:
titanic.describe()

,survived,pclass,age,sibsp,parch,fare
count,891.000000,891.000000,714.000000,891.000000,891.000000,891.000000
mean,0.383838,2.308642,29.699118,0.523008,0.381594,32.204208
std,0.486592,0.836071,14.526497,1.102743,0.806057,49.693429
min,0.000000,1.000000,0.420000,0.000000,0.000000,0.000000
25%,0.000000,2.000000,20.125000,0.000000,0.000000,7.910400
50%,0.000000,3.000000,28.000000,0.000000,0.000000,14.454200
75%,1.000000,3.000000,38.000000,1.000000,0.000000,31.000000
max,1.000000,3.000000,80.000000,8.000000,6.000000,512.329200


In [ ]:
import pandas as pd
data = {
    'name': ['Alice', 'Bob', 'Charlie', 'Diana'],
    'score': [88.5, 73.0, 91.0, 65.5]
}
df = pd.DataFrame(data)
df2 = df.drop(columns=['score'], inplace=False)
df.drop(columns=['name'], inplace=True)
print(df)
df2

   score
0   88.5
1   73.0
2   91.0
3   65.5


,name
0,Alice
1,Bob
2,Charlie
3,Diana


In [ ]:
for i in range(20):
  print(i* "**---------**")


**---------**
**---------****---------**
**---------****---------****---------**
**---------****---------****---------****---------**
**---------****---------****---------****---------****---------**
**---------****---------****---------****---------****---------****---------**
**---------****---------****---------****---------****---------****---------****---------**
**---------****---------****---------****---------****---------****---------****---------****---------**
**---------****---------****---------****---------****---------****---------****---------****---------****---------**
**---------****---------****---------****---------****---------****---------****---------****---------****---------****---------**
**---------****---------****---------****---------****---------****---------****---------****---------****---------****---------****---------**
**---------****---------****---------****---------****---------****---------****---------****---------****---------****---------**

In [ ]:
for i in range (1 , 100 ,2):
  print(i , end = " - " )

1 - 3 - 5 - 7 - 9 - 11 - 13 - 15 - 17 - 19 - 21 - 23 - 25 - 27 - 29 - 31 - 33 - 35 - 37 - 39 - 41 - 43 - 45 - 47 - 49 - 51 - 53 - 55 - 57 - 59 - 61 - 63 - 65 - 67 - 69 - 71 - 73 - 75 - 77 - 79 - 81 - 83 - 85 - 87 - 89 - 91 - 93 - 95 - 97 - 99 - 

In [ ]:
import seaborn as sns

titanic = sns.load_dataset('titanic')

In [ ]:
titanic


,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,0,2,male,27.0,0,0,13.0000,S,Second,man,True,NaN,Southampton,no,True
887,1,1,female,19.0,0,0,30.0000,S,First,woman,False,B,Southampton,yes,True
888,0,3,female,NaN,1,2,23.4500,S,Third,woman,False,NaN,Southampton,no,False
889,1,1,male,26.0,0,0,30.0000,C,First,man,True,C,Cherbourg,yes,True


In [ ]:
titanic[titanic['survived'] == 1 ]

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
8,1,3,female,27.0,0,2,11.1333,S,Third,woman,False,NaN,Southampton,yes,False
9,1,2,female,14.0,1,0,30.0708,C,Second,child,False,NaN,Cherbourg,yes,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
875,1,3,female,15.0,0,0,7.2250,C,Third,child,False,NaN,Cherbourg,yes,True
879,1,1,female,56.0,0,1,83.1583,C,First,woman,False,C,Cherbourg,yes,False
880,1,2,female,25.0,0,1,26.0000,S,Second,woman,False,NaN,Southampton,yes,False
887,1,1,female,19.0,0,0,30.0000,S,First,woman,False,B,Southampton,yes,True


In [ ]:
titanic[(titanic["embark_town"] == 'Southampton') & (titanic['who']=='man')]

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True
6,0,1,male,54.0,0,0,51.8625,S,First,man,True,E,Southampton,no,True
12,0,3,male,20.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True
13,0,3,male,39.0,1,5,31.2750,S,Third,man,True,NaN,Southampton,no,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
878,0,3,male,NaN,0,0,7.8958,S,Third,man,True,NaN,Southampton,no,True
881,0,3,male,33.0,0,0,7.8958,S,Third,man,True,NaN,Southampton,no,True
883,0,2,male,28.0,0,0,10.5000,S,Second,man,True,NaN,Southampton,no,True
884,0,3,male,25.0,0,0,7.0500,S,Third,man,True,NaN,Southampton,no,True


In [ ]:
rrr = titanic[(titanic['age'] <=10 ) | (titanic['age'] >= 70 )]
print(rrr)

     survived  pclass     sex    age  sibsp  parch     fare embarked   class  \
7           0       3    male   2.00      3      1  21.0750        S   Third   
10          1       3  female   4.00      1      1  16.7000        S   Third   
16          0       3    male   2.00      4      1  29.1250        Q   Third   
24          0       3  female   8.00      3      1  21.0750        S   Third   
43          1       2  female   3.00      1      2  41.5792        C  Second   
..        ...     ...     ...    ...    ...    ...      ...      ...     ...   
831         1       2    male   0.83      1      1  18.7500        S  Second   
850         0       3    male   4.00      4      2  31.2750        S   Third   
851         0       3    male  74.00      0      0   7.7750        S   Third   
852         0       3  female   9.00      1      1  15.2458        C   Third   
869         1       3    male   4.00      1      1  11.1333        S   Third   

       who  adult_male deck  embark_tow

In [ ]:
titanic

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,0,2,male,27.0,0,0,13.0000,S,Second,man,True,NaN,Southampton,no,True
887,1,1,female,19.0,0,0,30.0000,S,First,woman,False,B,Southampton,yes,True
888,0,3,female,NaN,1,2,23.4500,S,Third,woman,False,NaN,Southampton,no,False
889,1,1,male,26.0,0,0,30.0000,C,First,man,True,C,Cherbourg,yes,True


In [ ]:
values = titanic[(titanic["class"].isin(['First','Second']))]

In [ ]:
values

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
6,0,1,male,54.0,0,0,51.8625,S,First,man,True,E,Southampton,no,True
9,1,2,female,14.0,1,0,30.0708,C,Second,child,False,NaN,Cherbourg,yes,False
11,1,1,female,58.0,0,0,26.5500,S,First,woman,False,C,Southampton,yes,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
880,1,2,female,25.0,0,1,26.0000,S,Second,woman,False,NaN,Southampton,yes,False
883,0,2,male,28.0,0,0,10.5000,S,Second,man,True,NaN,Southampton,no,True
886,0,2,male,27.0,0,0,13.0000,S,Second,man,True,NaN,Southampton,no,True
887,1,1,female,19.0,0,0,30.0000,S,First,woman,False,B,Southampton,yes,True


In [ ]:
not_male = [~(titanic['sex']=='male')]

In [ ]:
not_male

[0      False
 1       True
 2       True
 3       True
 4      False
        ...  
 886    False
 887     True
 888     True
 889    False
 890    False
 Name: sex, Length: 891, dtype: bool]

In [ ]:
titanic.describe()

,survived,pclass,age,sibsp,parch,fare
count,891.000000,891.000000,714.000000,891.000000,891.000000,891.000000
mean,0.383838,2.308642,29.699118,0.523008,0.381594,32.204208
std,0.486592,0.836071,14.526497,1.102743,0.806057,49.693429
min,0.000000,1.000000,0.420000,0.000000,0.000000,0.000000
25%,0.000000,2.000000,20.125000,0.000000,0.000000,7.910400
50%,0.000000,3.000000,28.000000,0.000000,0.000000,14.454200
75%,1.000000,3.000000,38.000000,1.000000,0.000000,31.000000
max,1.000000,3.000000,80.000000,8.000000,6.000000,512.329200


In [ ]:
titanic[titanic['fare'] <10]

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True
5,0,3,male,NaN,0,0,8.4583,Q,Third,man,True,NaN,Queenstown,no,True
12,0,3,male,20.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
877,0,3,male,19.0,0,0,7.8958,S,Third,man,True,NaN,Southampton,no,True
878,0,3,male,NaN,0,0,7.8958,S,Third,man,True,NaN,Southampton,no,True
881,0,3,male,33.0,0,0,7.8958,S,Third,man,True,NaN,Southampton,no,True
884,0,3,male,25.0,0,0,7.0500,S,Third,man,True,NaN,Southampton,no,True


In [ ]:
missing_age = titanic[(titanic['age'])]

KeyError: "None of [Index([22.0, 38.0, 26.0, 35.0, 35.0,  nan, 54.0,  2.0, 27.0, 14.0,\n       ...\n       33.0, 22.0, 28.0, 25.0, 39.0, 27.0, 19.0,  nan, 26.0, 32.0],\n      dtype='float64', length=891)] are in the [columns]"

In [ ]:
missing_age

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
5,0,3,male,NaN,0,0,8.4583,Q,Third,man,True,NaN,Queenstown,no,True
17,1,2,male,NaN,0,0,13.0000,S,Second,man,True,NaN,Southampton,yes,True
19,1,3,female,NaN,0,0,7.2250,C,Third,woman,False,NaN,Cherbourg,yes,True
26,0,3,male,NaN,0,0,7.2250,C,Third,man,True,NaN,Cherbourg,no,True
28,1,3,female,NaN,0,0,7.8792,Q,Third,woman,False,NaN,Queenstown,yes,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
859,0,3,male,NaN,0,0,7.2292,C,Third,man,True,NaN,Cherbourg,no,True
863,0,3,female,NaN,8,2,69.5500,S,Third,woman,False,NaN,Southampton,no,False
868,0,3,male,NaN,0,0,9.5000,S,Third,man,True,NaN,Southampton,no,True
878,0,3,male,NaN,0,0,7.8958,S,Third,man,True,NaN,Southampton,no,True


In [ ]:
missing_age.shape[0]

177

In [ ]:
missing_age.shape[0]*100/titanic.shape[0]

19.865319865319865

In [ ]:
known_age =titanic[(titanic['age'].notna())]

In [ ]:
known_age.shape[0]

714

In [ ]:
titanic.sort_values(['age'],ascending=False)

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
630,1,1,male,80.0,0,0,30.0000,S,First,man,True,A,Southampton,yes,True
851,0,3,male,74.0,0,0,7.7750,S,Third,man,True,NaN,Southampton,no,True
493,0,1,male,71.0,0,0,49.5042,C,First,man,True,NaN,Cherbourg,no,True
96,0,1,male,71.0,0,0,34.6542,C,First,man,True,A,Cherbourg,no,True
116,0,3,male,70.5,0,0,7.7500,Q,Third,man,True,NaN,Queenstown,no,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
859,0,3,male,NaN,0,0,7.2292,C,Third,man,True,NaN,Cherbourg,no,True
863,0,3,female,NaN,8,2,69.5500,S,Third,woman,False,NaN,Southampton,no,False
868,0,3,male,NaN,0,0,9.5000,S,Third,man,True,NaN,Southampton,no,True
878,0,3,male,NaN,0,0,7.8958,S,Third,man,True,NaN,Southampton,no,True


In [ ]:
titanic.head(5)

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True


In [ ]:
sorted = titanic.sort_values(['pclass','age'], ascending=[ False, False ] )
sorted

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
851,0,3,male,74.0,0,0,7.7750,S,Third,man,True,NaN,Southampton,no,True
116,0,3,male,70.5,0,0,7.7500,Q,Third,man,True,NaN,Queenstown,no,True
280,0,3,male,65.0,0,0,7.7500,Q,Third,man,True,NaN,Queenstown,no,True
483,1,3,female,63.0,0,0,9.5875,S,Third,woman,False,NaN,Southampton,yes,True
326,0,3,male,61.0,0,0,6.2375,S,Third,man,True,NaN,Southampton,no,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
766,0,1,male,NaN,0,0,39.6000,C,First,man,True,NaN,Cherbourg,no,True
793,0,1,male,NaN,0,0,30.6958,C,First,man,True,NaN,Cherbourg,no,True
815,0,1,male,NaN,0,0,0.0000,S,First,man,True,B,Southampton,no,True
839,1,1,male,NaN,0,0,29.7000,C,First,man,True,C,Cherbourg,yes,True


In [ ]:
with open ('/content/Titanic-Dataset.csv','r') as file :
  file.read()

In [ ]:
import seaborn as sns
titanic = sns .load_dataset("titanic")

In [ ]:
titanic[titanic["sex"]=="female"][titanic["fare"].sum()]

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,0,2,male,27.0,0,0,13.0000,S,Second,man,True,NaN,Southampton,no,True
887,1,1,female,19.0,0,0,30.0000,S,First,woman,False,B,Southampton,yes,True
888,0,3,female,NaN,1,2,23.4500,S,Third,woman,False,NaN,Southampton,no,False
889,1,1,male,26.0,0,0,30.0000,C,First,man,True,C,Cherbourg,yes,True


In [ ]:
titanic[(titanic['age'] > 30) ].reset_index()

,index,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
1,3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
2,4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True
3,6,0,1,male,54.0,0,0,51.8625,S,First,man,True,E,Southampton,no,True
4,11,1,1,female,58.0,0,0,26.5500,S,First,woman,False,C,Southampton,yes,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
300,873,0,3,male,47.0,0,0,9.0000,S,Third,man,True,NaN,Southampton,no,True
301,879,1,1,female,56.0,0,1,83.1583,C,First,woman,False,C,Cherbourg,yes,False
302,881,0,3,male,33.0,0,0,7.8958,S,Third,man,True,NaN,Southampton,no,True
303,885,0,3,female,39.0,0,5,29.1250,Q,Third,woman,False,NaN,Queenstown,no,False


In [ ]:
titanic[(titanic['pclass']==1)&
(titanic['sex']=='female')&
(titanic['survived']==1)][['sex','age','fare']].sort_values(['fare'],ascending= False)

,sex,age,fare
258,female,35.0,512.3292
88,female,23.0,263.0000
341,female,24.0,263.0000
311,female,18.0,262.3750
742,female,21.0,262.3750
...,...,...,...
194,female,44.0,27.7208
11,female,58.0,26.5500
136,female,19.0,26.2833
796,female,49.0,25.9292


In [ ]:
titanic

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,0,2,male,27.0,0,0,13.0000,S,Second,man,True,NaN,Southampton,no,True
887,1,1,female,19.0,0,0,30.0000,S,First,woman,False,B,Southampton,yes,True
888,0,3,female,NaN,1,2,23.4500,S,Third,woman,False,NaN,Southampton,no,False
889,1,1,male,26.0,0,0,30.0000,C,First,man,True,C,Cherbourg,yes,True


In [ ]:
titanic.loc[4,"sex"]

'male'

In [ ]:
titanic.iloc[2,6]

np.float64(7.925)

In [ ]:
titanic["rakesh"] = titanic['age'] + titanic['sibsp']


In [ ]:
titanic

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone,rakesh
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False,23.0
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False,39.0
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True,26.0
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False,36.0
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True,35.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,0,2,male,27.0,0,0,13.0000,S,Second,man,True,NaN,Southampton,no,True,27.0
887,1,1,female,19.0,0,0,30.0000,S,First,woman,False,B,Southampton,yes,True,19.0
888,0,3,female,NaN,1,2,23.4500,S,Third,woman,False,NaN,Southampton,no,False,NaN
889,1,1,male,26.0,0,0,30.0000,C,First,man,True,C,Cherbourg,yes,True,26.0


In [ ]:
titanic.columns

Index(['survived', 'pclass', 'sex', 'age', 'sibsp', 'parch', 'fare',
       'embarked', 'class', 'who', 'adult_male', 'deck', 'embark_town',
       'alive', 'alone', 'rakesh'],
      dtype='object')

In [ ]:
import pandas as pd

In [ ]:
arranged_cols = ['rakesh','alone', 'survived', 'pclass', 'sex', 'age', 'sibsp', 'parch', 'fare',
       'embarked', 'class', 'who', 'adult_male', 'deck', 'embark_town',
       'alive']
titanic = titanic[arranged_cols]
titanic

TypeError: list indices must be integers or slices, not list

In [ ]:
arranged_cols =['survived','alone', 'survived', 'pclass', 'sex', 'age', 'sibsp', 'parch', 'fare',
       'embarked', 'class', 'who', 'adult_male', 'deck', 'embark_town','alive']
titanic = titanic[arranged_cols]
titanic

,survived,survived,alone,survived,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive
0,0,0,False,0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no
1,1,1,False,1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes
2,1,1,True,1,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes
3,1,1,False,1,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes
4,0,0,True,0,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,0,0,True,0,0,2,male,27.0,0,0,13.0000,S,Second,man,True,NaN,Southampton,no
887,1,1,True,1,1,1,female,19.0,0,0,30.0000,S,First,woman,False,B,Southampton,yes
888,0,0,False,0,0,3,female,NaN,1,2,23.4500,S,Third,woman,False,NaN,Southampton,no
889,1,1,True,1,1,1,male,26.0,0,0,30.0000,C,First,man,True,C,Cherbourg,yes


In [ ]:
import pandas as pd
import seaborn as sns

titanic = sns.load_dataset('titanic')

arranged_cols = [
     'alone', 'survived', 'pclass', 'sex', 'age',
    'sibsp', 'parch', 'fare', 'embarked', 'class', 'who',
    'adult_male', 'deck', 'embark_town', 'alive'
]

titanic = titanic[arranged_cols]
titanic

,alone,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive
0,False,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no
1,False,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes
2,True,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes
3,False,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes
4,True,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,True,0,2,male,27.0,0,0,13.0000,S,Second,man,True,NaN,Southampton,no
887,True,1,1,female,19.0,0,0,30.0000,S,First,woman,False,B,Southampton,yes
888,False,0,3,female,NaN,1,2,23.4500,S,Third,woman,False,NaN,Southampton,no
889,True,1,1,male,26.0,0,0,30.0000,C,First,man,True,C,Cherbourg,yes


In [ ]:
titanic["passenger_id"] = titanic["age"] + titanic["fare"]

In [ ]:
titanic

,alone,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,passenger_id
0,False,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,29.2500
1,False,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,109.2833
2,True,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,33.9250
3,False,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,88.1000
4,True,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,43.0500
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,True,0,2,male,27.0,0,0,13.0000,S,Second,man,True,NaN,Southampton,no,40.0000
887,True,1,1,female,19.0,0,0,30.0000,S,First,woman,False,B,Southampton,yes,49.0000
888,False,0,3,female,NaN,1,2,23.4500,S,Third,woman,False,NaN,Southampton,no,NaN
889,True,1,1,male,26.0,0,0,30.0000,C,First,man,True,C,Cherbourg,yes,56.0000


In [ ]:
titanic.columns

Index(['alone', 'survived', 'pclass', 'sex', 'age', 'sibsp', 'parch', 'fare',
       'embarked', 'class', 'who', 'adult_male', 'deck', 'embark_town',
       'alive', 'passenger_id'],
      dtype='object')

In [ ]:
rearr_col = ['passenger_id' ,'alone', 'survived', 'pclass', 'sex', 'age', 'sibsp', 'parch', 'fare',
       'embarked', 'class', 'who', 'adult_male', 'deck', 'embark_town',
       'alive']
titanic = titanic[rearr_col]
titanic
arranged_cols =['survived','alone', 'survived', 'pclass', 'sex', 'age', 'sibsp', 'parch', 'fare',
       'embarked', 'class', 'who', 'adult_male', 'deck', 'embark_town','alive']
titanic = titanic[arranged_cols]
titanic

,survived,alone,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive
0,0,False,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no
1,1,False,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes
2,1,True,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes
3,1,False,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes
4,0,True,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,0,True,0,2,male,27.0,0,0,13.0000,S,Second,man,True,NaN,Southampton,no
887,1,True,1,1,female,19.0,0,0,30.0000,S,First,woman,False,B,Southampton,yes
888,0,False,0,3,female,NaN,1,2,23.4500,S,Third,woman,False,NaN,Southampton,no
889,1,True,1,1,male,26.0,0,0,30.0000,C,First,man,True,C,Cherbourg,yes


In [ ]:
import numpy as np
import seaborn as sns


In [ ]:
data = {

       "age " :[ "rakesh",77,np.nan,True ],
      "name" : ["sumanth",89,np.nan,np.nan],
      "locaiton": ["irfan",77,np.nan,74]




}

In [ ]:
df = pd.DataFrame(data)
df

,age,name,locaiton
0,rakesh,sumanth,irfan
1,77,89,77
2,NaN,NaN,NaN
3,True,NaN,74


In [ ]:
rr = df.fillna(0)
rr

,age,name,locaiton
0,rakesh,sumanth,irfan
1,77,89,77
2,0,0,0
3,True,0,74


In [ ]:
df.isna()

,age,name,locaiton
0,False,False,False
1,False,False,False
2,False,False,False
3,False,False,False


In [ ]:
result = titanic[(titanic['sex'] == 'female') & (titanic['pclass'] == 1)]
result = result.sort_values('fare', ascending=False)
result = result.reset_index()
result.to_csv('female_class1.csv')


In [ ]:
result

,index,survived,survived,alone,survived,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive
0,258,1,1,True,1,1,1,female,35.0,0,0,512.3292,C,First,woman,False,NaN,Cherbourg,yes
1,88,1,1,False,1,1,1,female,23.0,3,2,263.0000,S,First,woman,False,C,Southampton,yes
2,341,1,1,False,1,1,1,female,24.0,3,2,263.0000,S,First,woman,False,C,Southampton,yes
3,311,1,1,False,1,1,1,female,18.0,2,2,262.3750,C,First,woman,False,B,Cherbourg,yes
4,742,1,1,False,1,1,1,female,21.0,2,2,262.3750,C,First,woman,False,B,Cherbourg,yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
89,194,1,1,True,1,1,1,female,44.0,0,0,27.7208,C,First,woman,False,B,Cherbourg,yes
90,11,1,1,True,1,1,1,female,58.0,0,0,26.5500,S,First,woman,False,C,Southampton,yes
91,136,1,1,False,1,1,1,female,19.0,0,2,26.2833,S,First,woman,False,D,Southampton,yes
92,796,1,1,True,1,1,1,female,49.0,0,0,25.9292,S,First,woman,False,D,Southampton,yes


In [ ]:
titanic

,survived,survived,alone,survived,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive
0,0,0,False,0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no
1,1,1,False,1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes
2,1,1,True,1,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes
3,1,1,False,1,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes
4,0,0,True,0,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,0,0,True,0,0,2,male,27.0,0,0,13.0000,S,Second,man,True,NaN,Southampton,no
887,1,1,True,1,1,1,female,19.0,0,0,30.0000,S,First,woman,False,B,Southampton,yes
888,0,0,False,0,0,3,female,NaN,1,2,23.4500,S,Third,woman,False,NaN,Southampton,no
889,1,1,True,1,1,1,male,26.0,0,0,30.0000,C,First,man,True,C,Cherbourg,yes


In [ ]:
titanic[(titanic['sex'] == 'female') & titanic['pclass'] == 1]


,survived,survived,alone,survived,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive
1,1,1,False,1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes
2,1,1,True,1,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes
3,1,1,False,1,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes
8,1,1,False,1,1,3,female,27.0,0,2,11.1333,S,Third,woman,False,NaN,Southampton,yes
10,1,1,False,1,1,3,female,4.0,1,1,16.7000,S,Third,child,False,G,Southampton,yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
879,1,1,False,1,1,1,female,56.0,0,1,83.1583,C,First,woman,False,C,Cherbourg,yes
882,0,0,True,0,0,3,female,22.0,0,0,10.5167,S,Third,woman,False,NaN,Southampton,no
885,0,0,False,0,0,3,female,39.0,0,5,29.1250,Q,Third,woman,False,NaN,Queenstown,no
887,1,1,True,1,1,1,female,19.0,0,0,30.0000,S,First,woman,False,B,Southampton,yes


In [ ]:
titanic['fare_category'] = titanic['fare']


/tmp/ipykernel_8434/4158515090.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  titanic['fare_category'] = titanic['fare']


In [ ]:
titanic

,survived,survived,alone,survived,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,fare_category
0,0,0,False,0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,7.2500
1,1,1,False,1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,71.2833
2,1,1,True,1,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,7.9250
3,1,1,False,1,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,53.1000
4,0,0,True,0,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,8.0500
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,0,0,True,0,0,2,male,27.0,0,0,13.0000,S,Second,man,True,NaN,Southampton,no,13.0000
887,1,1,True,1,1,1,female,19.0,0,0,30.0000,S,First,woman,False,B,Southampton,yes,30.0000
888,0,0,False,0,0,3,female,NaN,1,2,23.4500,S,Third,woman,False,NaN,Southampton,no,23.4500
889,1,1,True,1,1,1,male,26.0,0,0,30.0000,C,First,man,True,C,Cherbourg,yes,30.0000


In [ ]:
tt =titanic[titanic['sex'] == 'female']
tt

,survived,survived,alone,survived,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,fare_category
1,1,1,False,1,1,1,female,50.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,71.2833
2,1,1,True,1,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,7.9250
3,1,1,False,1,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,53.1000
8,1,1,False,1,1,3,female,27.0,0,2,11.1333,S,Third,woman,False,NaN,Southampton,yes,11.1333
9,1,1,False,1,1,2,female,14.0,1,0,30.0708,C,Second,child,False,NaN,Cherbourg,yes,30.0708
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
880,1,1,False,1,1,2,female,25.0,0,1,26.0000,S,Second,woman,False,NaN,Southampton,yes,26.0000
882,0,0,True,0,0,3,female,22.0,0,0,10.5167,S,Third,woman,False,NaN,Southampton,no,10.5167
885,0,0,False,0,0,3,female,39.0,0,5,29.1250,Q,Third,woman,False,NaN,Queenstown,no,29.1250
887,1,1,True,1,1,1,female,19.0,0,0,30.0000,S,First,woman,False,B,Southampton,yes,30.0000


In [ ]:
titanic.loc[1, 'age'] = 50
titanic

,survived,survived,alone,survived,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,fare_category
0,0,0,False,0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,7.2500
1,1,1,False,1,1,1,female,50.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,71.2833
2,1,1,True,1,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,7.9250
3,1,1,False,1,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,53.1000
4,0,0,True,0,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,8.0500
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,0,0,True,0,0,2,male,27.0,0,0,13.0000,S,Second,man,True,NaN,Southampton,no,13.0000
887,1,1,True,1,1,1,female,19.0,0,0,30.0000,S,First,woman,False,B,Southampton,yes,30.0000
888,0,0,False,0,0,3,female,NaN,1,2,23.4500,S,Third,woman,False,NaN,Southampton,no,23.4500
889,1,1,True,1,1,1,male,26.0,0,0,30.0000,C,First,man,True,C,Cherbourg,yes,30.0000
